name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pypi-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - run: python -m pip install --upgrade pip build wheel
      - run: python -m build --sdist --wheel
      - uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - pypi-build
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: release-dists
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1

  npmjs:
    name: npmjs.org
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@latest
      - run: npm ci
      - run: npm config set git-tag-version=false
      - run: npm version ${{ github.event.release.tag_name }}
      - run: npm run build --if-present
      - run: npm publish
